sudo: false
language: go
go:
  - 1.7
  - 1.8
  - 1.9
  - tip
matrix:
  fast_finish: true
  allow_failures:
    - go: tip
    - go: 1.7
branches:
 only:
  - master
before_install:
  - cd $GOPATH/src/github.com/pjgg/rest-in-peace
  - go get -t -v ./...
install: 
  - go build -v -ldflags "-X main.version=$TRAVIS_TAG -s -w" -o bin/rest-in-peace-$TRAVIS_TAG ./jsonAssert
script: 
  - go test -v -race -coverprofile=coverage.txt -covermode=atomic ./jsonAssert
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
  - pablo.gonzalez.granados@gmail.com